version: "3.8"
services:
  proxy_svc:
    build: svc/proxy
    depends_on: 
      - api_svc
    restart: always
    ports:
      - "8080:8080"
  api_svc:
    build: svc/api
    depends_on:
      - shortcut_svc
    restart: always
    environment: 
      PORT: ':9090'
      SHORTCUT_ADDR: 'shortcut_svc:9092'
    ports:
      - "9090:9090"
  shortcut_svc:
    build: svc/shortcut
    depends_on: 
      - database_svc
    restart: always
    environment: 
      PORT: ':9092'
      DB_HOST: 'database_svc'
      DB_USER: 'root'
      DB_PASS: 'root'
      DB_NAME: 'db'

  database_svc:
    # Connect to db: docker exec <container name> bash
    #                $ mysql -u <user> -p -h127.0.0.1
    #                $ <password>
    image: mysql
    volumes: 
      - ./svc/db:/docker-entrypoint-initdb.d
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 'root' 
      MYSQL_DATABASE: 'db'
    cap_add:
      - SYS_NICE
